settings:
  ## Base configuration
  # The root of the backup directory tree
  # [required]
  root: /srv/backup
  # The logical volume path (vg/lv) corresponding to the backup root
  # [required]
  backup-lv: backups/current
  # The minimum free percentage of a resource, below which
  # "multibackup df -c" will complain
  # [default: 5]
  df-warning: 10

  ## Garbage-collection timing
  # The number of days to retain multiple snapshots per day
  # [default: 14]
  gc-duplicate-days: 14
  # The number of weeks to retain one backup per day
  # [default: 8]
  gc-daily-weeks: 8
  # The number of ISO 8601 (28-day) months to retain one backup per week
  # [default: 12]
  gc-weekly-months: 12
  # The number of backup logs to retain per instance
  # [default: 60]
  gc-log-distinct-days: 60

  ## coda source
  # The probability that a full dump will be perfomed on a Coda volume
  # [default: 0.143]
  coda-full-probability: 0.5
  # The path to volutil on the Coda server
  # [default: volutil]
  coda-volutil-path: /usr/sbin/volutil
  # The path to codadump2tar on the Coda server
  # [default: codadump2tar]
  coda-codadump2tar-path: /usr/sbin/codadump2tar
  # Number of simultaneous backup jobs
  # [default: 1]
  coda-workers: 2

  ## github source
  # OAuth token obtained from "multibackup github auth"
  # [required]
  github-token: my_token
  # The probability that the data and metadata for a repository will be
  # revalidated
  # [default: 0.0333]
  github-scrub-probability: 0.0333
  # The path to git on the local server
  # [default: git]
  github-git-path: /usr/local/bin/git
  # Number of simultaneous backup jobs
  # [default: 1]
  github-workers: 2

  ## rbd source
  # Number of simultaneous backup jobs
  # [default: 1]
  rbd-workers: 2

  ## rgw source
  # The radosgw server
  # [required]
  rgw-server: storage.example.org
  # Whether to connect to radosgw over SSL
  # [default: false]
  rgw-secure: false
  # The probability that object ACLs will be unconditionally fetched for a
  # bucket, even for objects that have not changed
  # [default: 0.0166]
  rgw-force-acl-probability: 0.01
  # Number of fetch threads per backup job
  # [default: 4]
  rgw-threads: 4
  # Number of simultaneous backup jobs
  # [default: 1]
  rgw-workers: 2

  ## rsync source
  # The path to rsync on the backup server
  # [default: rsync]
  rsync-local-binary: /usr/local/bin/rsync
  # A list of rsync exclude patterns to be applied to all backups
  # [default: no exclusions]
  rsync-exclude:
    - /tmp/*
    - /var/tmp/*
  # The probability that a host's backup will be revalidated by comparing
  # backup data to the original
  # [default: 0.0166]
  rsync-scrub-probability: 0.0166
  # Number of simultaneous backup jobs
  # [default: 1]
  rsync-workers: 2

## Backup targets for coda source
coda:
  # A set of volume replicas
  # [default: no sets]
  -
    # The FQDNs of the servers that host replicas for these volumes
    # [required]
    servers:
      - coda1.example.org
      - coda2.example.org
    # The list of volumes
    # [required]
    volumes:
      - a:foo
      - a:bar
      - a:baz

## Backup targets for github source
github:
  # A GitHub organization
  # [default: no organizations]
  jquery:
    # Whether to back up organization metadata (team membership, etc.)
    # Requires an account with admin access to the organization.
    # [default: true]
    organization-metadata: true

## Backup targets for rbd source
rbd:
  # An RBD pool
  # [default: no pools]
  pool-1:
    # Images to back up
    # [default: no images]
    images:
      # A human-readable name for the image, and its RBD name
      foo-data: volume-be220107-966d-4253-93c7-d33cdfe18166
    # Snapshots to back up
    # [default: no snapshots]
    snapshots:
      # A human-readable name for the snapshot, and its RBD name
      foo-data-20140301: snapshot-d023e06a-15c2-4c9f-953c-7d22b2fb5b39

## Backup targets for rgw source
rgw:
  # Buckets to back up
  # [default: no buckets]
  - bucket1

## Backup targets for rsync source
rsync:
  # FQDN of host
  # [default: no hosts]
  host1.example.org:
    # Filesystem mountpoints to back up
    # [required]
    mounts:
      - /
      - /boot
    # The subdirectory to store backups into
    # [default: hostname up to the first dot]
    alias: octopus
    # Command to run on remote system before backup
    # [default: no command]
    pre: /usr/local/bin/database_snapshot --create
    # Command to run on remote system after backup
    # (whether or not the backup was successful)
    # [default: no command]
    post: /usr/local/bin/database_snapshot --delete
    # A list of rsync exclude patterns to be applied, in addition to the
    # global list of exclude patterns
    # [default: no patterns]
    exclude:
      - /var/lib/mysql/*
