settings:
  root: /srv/backup
  backup-lv: backups/current
  coda-full-probability: 0.5
  coda-volutil-path: /usr/sbin/volutil
  coda-codadump2tar-path: /usr/sbin/codadump2tar
  gc-duplicate-days: 14
  gc-daily-weeks: 8
  gc-weekly-months: 12
  rgw-force-acl-probability: 0.01
  rgw-server: storage.example.org
  rgw-secure: false
  rgw-threads: 4
  rsync-local-binary: /usr/local/bin/rsync
  rsync-exclude:
    - /tmp/*
    - /var/tmp/*
  coda-workers: 2
  rbd-workers: 2
  rgw-workers: 2
  rsync-workers: 2
rsync:
  host1.example.org:
    mounts: [/, /boot]
  host2.example.org:
    mounts: [/]
    pre: /usr/local/bin/database_snapshot --create
    post: /usr/local/bin/database_snapshot --delete
    exclude:
      - /var/lib/mysql/*
rgw:
  - bucket1
  - bucket2
rbd:
  pool-1:
    images:
      foo-data: volume-be220107-966d-4253-93c7-d33cdfe18166
      bar: volume-64c39781-8c86-433b-9952-82200bb476a6
    snapshots:
      foo-data-20140301: snapshot-d023e06a-15c2-4c9f-953c-7d22b2fb5b39
coda:
  -
    servers:
      - coda1.example.org
      - coda2.example.org
    volumes:
      - a:foo
      - a:bar
      - a:baz
  -
    servers:
      - coda3.example.org
      - coda4.example.org
    volumes:
      - b:xyzzy
      - b:plugh
