settings:
  ## Base configuration
  # The root of the backup directory tree
  # [required]
  root: /srv/backup
  # The logical volume path (vg/lv) corresponding to the backup root
  # [required]
  backup-lv: backups/current
  # The minimum free percentage of a resource, below which "deltaic df -c"
  # will complain
  # [default: 5]
  df-warning: 10

  ## Garbage-collection timing
  # The number of days to retain multiple snapshots per day
  # [default: 14]
  gc-duplicate-days: 14
  # The number of weeks to retain one backup per day
  # [default: 8]
  gc-daily-weeks: 8
  # The number of ISO 8601 (28-day) months to retain one backup per week
  # [default: 12]
  gc-weekly-months: 12
  # The number of backup logs to retain per instance
  # [default: 60]
  gc-log-distinct-days: 60

  ## coda source
  # The probability that a full dump will be perfomed on a Coda volume
  # [default: 0.143]
  coda-full-probability: 0.5
  # The path to volutil on the Coda server
  # [default: volutil]
  coda-volutil-path: /usr/sbin/volutil
  # The path to codadump2tar on the Coda server
  # [default: codadump2tar]
  coda-codadump2tar-path: /usr/sbin/codadump2tar
  # Number of simultaneous backup jobs
  # [default: 1]
  coda-workers: 2

  ## github source
  # OAuth token obtained from "deltaic github auth"
  # [required]
  github-token: my_token
  # The probability that the data and metadata for a repository will be
  # revalidated
  # [default: 0.0166]
  github-scrub-probability: 0.0166
  # The path to git on the local server
  # [default: git]
  github-git-path: /usr/local/bin/git
  # Number of simultaneous backup jobs
  # [default: 1]
  github-workers: 2

  ## rbd source
  # The probability that a backup will be validated by comparing its data
  # to the original
  # [default: 0.0166]
  rbd-scrub-probability: 0.0166
  # Number of simultaneous backup jobs
  # [default: 1]
  rbd-workers: 2

  ## rgw source
  # The radosgw server
  # [required]
  rgw-server: storage.example.org
  # Whether to connect to radosgw over SSL
  # [default: false]
  rgw-secure: false
  # The probability that object ACLs will be unconditionally refreshed for
  # a bucket, even for objects that have not changed
  # [default: 0]
  rgw-scrub-acl-probability: 0.01
  # The probability that a bucket will be revalidated by comparing backup
  # data and metadata to the original
  # [default: 0.0166]
  rgw-scrub-probability: 0.01
  # Number of fetch threads per backup job
  # [default: 4]
  rgw-threads: 4
  # Number of simultaneous backup jobs
  # [default: 1]
  rgw-workers: 2

  ## rsync source
  # The path to rsync on the backup server
  # [default: rsync]
  rsync-local-binary: /usr/local/bin/rsync
  # A list of rsync exclude patterns to be applied to all backups
  # [default: no exclusions]
  rsync-exclude:
    - /tmp/*
    - /var/tmp/*
  # The probability that a host's backup will be revalidated by comparing
  # backup data to the original
  # [default: 0.0166]
  rsync-scrub-probability: 0.0166
  # Number of simultaneous backup jobs
  # [default: 1]
  rsync-workers: 2

  ## Offsite archive settings
  # Temporary filesystem for archive data
  # [required for archiving]
  archive-spool: /srv/spool
  # GPG key identifier for signing archives
  # [required for archive encryption]
  archive-gpg-signing-key: 0123456789abcdef
  # Recipient GPG key identifiers
  # [required for archive encryption]
  archive-gpg-recipients:
    - 0123456789fedcba
  # The path to tar on the local server
  # [default: tar]
  archive-tar-path: /usr/local/bin/tar
  # The path to gpg on the local server
  # [default: gpg2]
  archive-gpg-path: /usr/local/bin/gpg2

  ## Archiver profiles
  # [required for archiving]
  archivers:
    # Default profile
    default:
      ## aws archiver
      # Select archiver
      # [required]
      archiver: aws
      # AWS access key ID
      # [required]
      aws-access-key-id: value
      # AWS secret access key
      # [required]
      aws-secret-access-key: value
      # AWS region
      # [required]
      aws-region: us-east-1
      # Name of Glacier vault and SimpleDB domain
      # [required]
      aws-namespace: vault-name
      # Storage cost per GB-month in selected region
      # [default: 0.01]
      aws-storage-cost: 0.012
      # Default archive compression (gzip, lzop, none)
      # [default: gzip]
      compression: lzop
      # Number of snapshots to keep archived
      # [default: 1]
      keep-count: 1
      # Number of simultaneous archive jobs
      # [default: 8]
      workers: 8

## Backup units for coda source
coda:
  # A set of volume replicas
  # [default: no sets]
  -
    # The FQDNs of the servers that host replicas for these volumes
    # [required]
    servers:
      - coda1.example.org
      - coda2.example.org
    # The list of volumes
    # [required]
    volumes:
      - a:foo
      - a:bar
      - a:baz

## Backup units for github source
github:
  # A GitHub organization
  # [default: no organizations]
  jquery:
    # Whether to back up organization metadata (team membership, etc.)
    # Requires an account with admin access to the organization.
    # [default: true]
    organization-metadata: true

## Backup units for rbd source
rbd:
  # An RBD pool
  # [default: no pools]
  pool-1:
    # Images to back up
    # [default: no images]
    images:
      # A human-readable name for the image, and its RBD name
      foo-data: volume-be220107-966d-4253-93c7-d33cdfe18166
    # Snapshots to back up
    # [default: no snapshots]
    snapshots:
      # A human-readable name for the snapshot, and its RBD name
      foo-data-20140301: snapshot-d023e06a-15c2-4c9f-953c-7d22b2fb5b39

## Backup units for rgw source
rgw:
  # Buckets to back up
  # [default: no buckets]
  - bucket1

## Backup units for rsync source
rsync:
  # FQDN of host
  # [default: no hosts]
  host1.example.org:
    # Filesystem mountpoints to back up
    # [required]
    mounts:
      - /
      - /boot
    # The subdirectory to store backups into
    # [default: hostname up to the first dot]
    alias: octopus
    # Command to run on remote system before backup
    # [default: no command]
    pre: /usr/local/bin/database_snapshot --create
    # Command to run on remote system after backup
    # (only if the backup was successful)
    # [default: no command]
    post: /usr/local/bin/database_snapshot --delete
    # A list of rsync exclude patterns to be applied, in addition to the
    # global list of exclude patterns
    # [default: no patterns]
    exclude:
      - /var/lib/mysql/*

## Unit configuration for archiver profiles
archivers:
  # Default profile
  default:
    # Unit name
    rgw/bucket1:
      # Archive compression (gzip, lzop, none)
      # [default: value of compression setting in archiver profile]
      compression: lzop
